# Generated by Django 4.2.3 on 2023-08-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LApp', '0002_user_pfimg_tchprofile_stprofile_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprofile',
            name='sstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tchprofile',
            name='tstatus',
            field=models.BooleanField(default=False),
        ),
    ]
