# Generated by Django 4.2.3 on 2023-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LApp', '0003_stprofile_sstatus_tchprofile_tstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='appldate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(),
        ),
    ]
